name: winhealth_admin_v2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  chips_choice: ^3.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  file_saver: ^0.2.9
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  pinput: ^4.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
